### ISSUE TITLE
Lazy loading seems not working.

### ISSUE THREAD

**Issue by lorenzomelato** [isc30/blazor-lazy-loading#64] opened 2020-07-06 21:26 UTC
I have just tried the demo here:
https://github.com/isc30/blazor-lazy-loading/issues?q=is%3Aissue+is%3Aopen

From what I see from the network tab in the chrome dev tools and with fiddler also It seems that all the assemblies are downloaded at the application startup and not at the time of the first usage of the component.

Is there something wrong in my tests?

**Comment by isc30** [comment] 2020-07-06 22:35
Hi, please disable linker if you want the full lazy experience. This is caused by #60 which is out of my hands. Even if the download happens during startup, the assemblies are loaded later. Waiting for that bug to be fixed to support the full experience with linker enabled.

**Comment by isc30** [comment] 2020-07-09 07:33
Closing the issue, please let me know if disabling the linker worked.

**Closed by isc30** 2020-07-09 07:33 UTC
Labels: bug, duplicate
